#define uint unsigned int
extern int   write(int fd, char* buffer, int count);
extern float sinf(float val);
extern float cosf(float val);
extern int   glfwInit(void);
extern void  glfwWindowHint(int hint, int value);
extern void* glfwCreateWindow(int width, int height, void* title, void* monitor, void* share);
extern void  glfwMakeContextCurrent(void* window);
extern void  glfwSwapBuffers(void* window);
extern void  glfwPollEvents(void);
extern int   glfwWindowShouldClose(void* window);
extern void  glfwGetFramebufferSize(void* window,  int* width, int* height);
extern int   glfwGetKey(void* window, uint key);
extern void  glfwTerminate(void);
extern uint  glfwGetError(char** error);
extern void  glGenVertexArrays(uint count, void* arrays);
extern void  glGenBuffers(uint count, void* buffers);
extern void  glBindVertexArray(uint array);
extern void  glBindBuffer(uint target, uint buf);
extern void  glBufferData(uint target, uint size, void* data, uint usage);
extern void  glVertexAttribPointer(uint index, uint size, uint type, int normalized, uint stride, void* pointer);
extern void  glEnableVertexAttribArray(uint index);
extern uint  glCreateShader(uint type);
extern void  glShaderSource(uint shader, uint count, void* sources, void* lengths); //String is a double pointer to a string
extern void  glCompileShader(uint shader);
extern void  glGetShaderiv(uint shader, uint param, void* returnval);
extern void  glGetShaderInfoLog(uint shader, uint bufsize, void* returnsize, void* buf);
extern void  glDeleteShader(uint shader);
extern uint  glCreateProgram(void);
extern void  glAttachShader(uint program, uint shader);
extern void  glLinkProgram(uint program);
extern void  glGetProgramiv(uint program, uint param, void* returnval);
extern void  glGetProgramInfoLog(uint program, uint bufsize, void* returnsize, void* buf);
extern void  glDetachShader(uint program, uint shader);
extern void  glDeleteProgram(uint program);
extern void  glUseProgram(uint program);
extern uint  glGetUniformLocation(uint program, char* name);
extern void  glClearColor(float r, float g, float b, float a);
extern void  glClear(uint flags);
extern void  glDrawElements(uint drawtype, uint count, uint elemtype, uint offset);
extern void  glUniform2f(uint uniform, float v1, float v2);
extern void  glUniform2fv(uint uniform, uint count, float* values);
extern void  glUniform3fv(uint uniform, uint count, float* values);
extern void  glViewport(int x, int y, int width, int height);
extern uint  glGetError(void);